include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude: ['lib/generated_plugin_registrant.dart']
  strong-mode:
    implicit-dynamic: true
  language:
    strict-inference: false

linter:
  rules:
    unnecessary_lambdas: false
    omit_local_variable_types: false
    sort_pub_dependencies: false
