name: rickerest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.13
  firebase_core: 1.14.0
  flutterfire_ui: 0.4.0+1
  get: 4.6.1
  url_strategy: 0.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  pedantic_mono: 1.17.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

