name: rickerest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.13
  firebase_core: 1.14.0
  flutterfire_ui: 0.4.0+1
  get: 4.6.1
  cloud_firestore: 3.1.11
  getwidget: 2.0.5
  flex_color_scheme: 4.2.0
  google_fonts: 2.3.1
  get_storage: 2.0.3
  awesome_select: 5.2.0
  nil: 1.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  pedantic_mono: 1.17.0
  flutter_launcher_icons: 0.9.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icon/
  uses-material-design: true

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true

