name: rickerest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  flutterfire_ui: ^0.4.0+2
  get: 4.6.1
  cloud_firestore: ^3.1.12
  getwidget: 2.0.5
  flex_color_scheme: 4.2.0
  google_fonts: 2.3.1
  awesome_select: 5.2.0
  nil: 1.1.1
  convex_bottom_bar: 3.0.0
  easy_dynamic_theme: 2.2.0
  cached_network_image: 3.2.0
  objectbox: 1.4.1
  simple_logger: 1.9.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  pedantic_mono: 1.17.0
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icon/
  uses-material-design: true

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true

