name: rickerest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.13
  firebase_core: 1.14.0
  flutter:
    sdk: flutter
  flutterfire_ui: 0.4.0+1
  get: 4.6.1

dev_dependencies: 
  flutter_test:
    sdk: flutter
  pedantic_mono: 1.17.0

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

